### ISSUE TITLE
Reference Assemblies experiment

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspLabs#1]
The goals of this experiment are:
- Simplify the user experience with respect to referencing ASP.NET Core as a product
- Less moving parts when deploying (can we stop deploying redundant things?)
- Get the crossgen (native compiled) benefits on dev boxes and on azure

We have tried solved some of these things with meta packages and the package cache but it's been a bit of a grab bag so far. Also, we haven't come up with anything to solve the less moving parts problem.

These assemblies would come in nuget packages of the same name. This works well for references but there are questions about where we get the implementations from. Here are some ideas:
- **Shared Framework** - Should we bundle with the shared framework on .NET Core?
- **Zip** - Random zip full of DLLs that the user can put in a "loadable" location. This is iffy as it isn't integrated with any toolchain but maybe it'll be fine as it's simpler to reason about (folder full of DLLs you can drop in the bin or GAC zomg, or copy around).
- **NuGet** - We can offer nuget packages as a better alternative to the zip. They wouldn't be what we have today, it would be a single package with all of the runtime implementations. e.g. Microsoft.AspNetCore.Standalone, Microsoft.Extensions.Standalone. This would be used to make things xcopyable. What's interesting is that we have this pivot today with Microsoft.NETCore.App but we're using "type": "platform" to describe standalone vs not.
### Our engineering

We keep the packages we have today as they work nicely for us. Each repo produces their packages and depend on other packages. Packages are our replacement for assemblies in this world and we get the benefits of feeds to push and pull packages between repos. We have a build process that would take these packages and turn them into the appropriate reference assembly groups. You cannot use the packages we produce with the reference assembly packages. If you want to use nightly builds, you need to what we do today, reference the atoms (what I'm calling packages), the same goes for customers. Our packages also never make it to nuget.org, they will only ever be on myget.

We need to test drive an end to end experience to find the wrinkles:
- A custom shared framework with ASP.NET Core
- Packages for **Microsoft.AspNetCore** and **Microsoft.Extensions**
- Test drive the deployment/development experience

**Comment by muratg** [comment]
What's in Microsoft.Extensions?

**Comment by grahamehorner** [comment]
+1 for MyGet packages

**Comment by natemcmaster** [comment]
Closing as this experiment has been abandoned.
