### ISSUE TITLE
RunProxy Uses Default Timeout

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#101]
_From @Tratcher on Thursday, March 30, 2017 9:41:02 PM_

_From @AceCoderLaura on March 31, 2017 3:56_

When using a proxy to redirect calls from ASP to my WCF service, timeouts occur. I suspect that the proxy's HttpClient is using the default request timeout. There needs to be a way to set the timeout.

```
app.MapWhen(c => IsWCFCall(c), builder =>
{
    builder.RunProxy(new ProxyOptions { Scheme = "http", Host = "localhost", Port = XivicConfiguration.WCFPort.ToString() });
});
```

Apologies if this is the wrong repository.

_Copied from original issue: aspnet/Home#1981_

_Copied from original issue: aspnet/Proxy#58_

**Comment by davidfowl** [comment]
See https://github.com/microsoft/reverse-proxy for future proxy improvements
