### ISSUE TITLE
Dynamically and conditionally selecting target url

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#103]
_From @hikalkan on Monday, October 9, 2017 11:10:37 PM_

Think that I'm creating an application;

* Forwards /api/service1/... -> https://domain1.com/api/service1/...
* Forwards /api/service2/... -> https://domain1.com/api/service2/...

And does nothing (does not forward) for other URLs (example: /api/service3).

Thus, we can forward some URLs but also use MVC framework to provide other services in our application.

So, we need to a configuration option: a mapping or URLs

_Copied from original issue: aspnet/Proxy#70_

**Comment by davidfowl** [comment]
See https://github.com/microsoft/reverse-proxy

**Comment by hikalkan** [comment]
Thanks @davidfowl
