### ISSUE TITLE
Suggestion: SharedProxyOptions.MessageHandler should be a Func that returns the MessageHandler

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#104]
_From @adamholdenyall on Thursday, November 2, 2017 2:08:28 PM_

I have spent a good chunk of time chasing down an issue where a long running request through the proxy deadlocked other short requests until it finished. I finally narrowed it down to the fact that it was using the same MessageHandler for every request, and HttpClientHandler only seems to support one request at a time (I am on an older version of Core fwiw). 

It may be best to make this option a function so that the user can create a new instance of the MessageHandler for each request to avoid deadlocks.

_Copied from original issue: aspnet/Proxy#72_

**Comment by davidfowl** [comment]
All proxy work has moved to https://github.com/microsoft/reverse-proxy.
