### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#105]
_From @grahamehorner on Tuesday, November 28, 2017 10:05:36 AM_

Please provide more samples on how to use the Proxy middleware; dynamic routing and/or selective routing of URIs to backend services etc. 

_Copied from original issue: aspnet/Proxy#77_

**Comment by davidfowl** [comment]
All proxy work has moved to https://github.com/microsoft/reverse-proxy.
