### ISSUE TITLE
Add grouping possibility for the check 

### ISSUE THREAD

**Issue by damienbod** [aspnet/AspLabs#13]
Tags maybe...

**Comment by JuergenGutsch** [comment]
Maybe like this:
```
services.AddHealthChecks(checks => {
                checks.AddUrlCheck("https://github.com");
                checks.AddHealthCheckGroup("memory", group => { // group is a HealthCheckBuilder
                                group.AddPrivateMemorySizeCheck(1);
                                group.AddVirtualMemorySizeCheck(2);
                });
                checks.AddWorkingSetCheck(1);
                checks.AddUrlChecks(new List<string> { "https://github.com", "https://google.com", "https://twitddter.com" }, "servers");
            });
```
A HealtCheckGroup could technically be a simple HealthCheck that just checks other HealthChecks

**Comment by damienbod** [comment]
We could also add a strict parameter to the group.

If 0 child items are Healthy => Unhealthy
childItems Healthy >0 < max => Unhealthy, Warning depending on strict parameter
max healthy => Healthy

The group could then be handled as a unit. Child items are only evaluated as part of the group. 

Greetings Damien

**Comment by natemcmaster** [comment]
Closing as this issue is stale. HealthChecks has moved into production. Use https://github.com/aspnet/AspNetCore for issues on this feature in the future.
