### ISSUE TITLE
Webhooks Remove dependency on User for Core Interfaces

### ISSUE THREAD

**Issue by nitro52** [aspnet/AspLabs#143]
We are currently implementing Webhooks and noticed that many of the core Interfaces depend on a UserId string, for example IWebHookStore. This ties the implementation to a per user registration which is not always suitable. For example our setup requires registrations to be globally for all users because we have an instance per client that contains multiple users. The WebHooks relate to the client not their users.  

It seems like the dependency on User can be abstracted easy enough and replaced with simply a registration container Id or something like that. Then at the Microsoft.AspNet.WebHooks.Custom.Api level it would simply use the User Id as the container ID. This would also allow some or the core libraries to be used outside of Asp.net. For example a desktop app that wants to Send WebHook Events.

**Comment by dougbu** [comment]
Thank-you for your interest in this project. We are not actively expanding this project at this time. And, this suggestion would be a significant breaking change.

**Comment by nitro52** [comment]
Would this be a breaking change? the parameter type for the UserId is already a string. For the most part it seems like a simple rename of parameters/documentation.
