### ISSUE TITLE
Windows Authentication behind proxy

### ISSUE THREAD

**Issue by cbmek** [aspnet/AspLabs#158]
Hi, I try to use Proxy to direct traffic to service witch uses Windows Authentication (Negotiate/NTLM on IIS).
Direct traffic to my service works ok and users are autenticated, but when I direct traffic through Proxy (installed on other server) I doesn't work. I've tried to switch the servers, to make sure they are both configured the same way. I got **Anonymous and Windows Authentication** on my service. I got only **Anonymous Authentication** on Proxy.

My Proxy code:
```csharp
            services.AddProxy(o =>
            {
                o.PrepareRequest = (originalRequest, message) =>
                {
                    message.Headers.Add("X-Forwarded-Host", $"{originalRequest.Host}");
                    message.Headers.Add("X-Forwarded-Proto", $"{originalRequest.Scheme}");
                    message.Headers.Add("X-Forwarded-For", $"{originalRequest.HttpContext.Connection.RemoteIpAddress}");
                    return Task.FromResult(0);
                };
            });
```
```csharp
            app.MapWhen(x => x.Request.Path.StartsWithSegments("/my-service"), c => c.RunProxy(_destUrl));
```
Someone [HERE](https://forums.asp.net/t/2132450.aspx?Is+windows+authentication+supported+by+Microsoft+AspNetCore+Proxy+) suggested that it may be due to connections not persisting connections during Negotiate (and Windows Authentication requires it) - but I'm not sure if it's a case.

Please advice.

**Comment by davidfowl** [comment]
All proxy work has moved to https://github.com/microsoft/reverse-proxy.
