### ISSUE TITLE
Why i can not create my own WebHook?

### ISSUE THREAD

**Issue by LightVolk** [aspnet/AspLabs#185]
### Describe the bug

I try to create my own WebHook class:

```
using Microsoft.Extensions.DependencyInjection;
using System;
using Microsoft.AspNetCore.WebHooks.Metadata;   //error! Not found!

namespace MyProject.Extensions
{
    public static class MyWebHookExtension
    {
        public static void AddMyWebHookServices(IServiceCollection services)
        {
            if (services == null)
            {
                throw new ArgumentNullException(nameof(services));
            }

      //      WebHookMetadata.Register<WebSubMetadata>(services);   // i can not resolve this reference!
        }
    }
}


```
### To Reproduce
1. Using this version of ASP.NET Core '2.2'

### Screenshots
![image](https://user-images.githubusercontent.com/1236916/56836327-93b8ae00-687f-11e9-95a4-83675c1f7167.png)

### Additional context
I try to find some documentation about creating my own WebHook, but i can not.
Found [this article](https://www.tpeczek.com/2018/05/under-hood-of-aspnet-core-webhooks.html). But i can not resolve WebHostMetadata class.

Should i add some packages?

**Comment by Eilon** [comment]
Can you show what error you are getting? The `WebSubMetadata` type looks like a custom type written by the author of the blog post.

**Comment by LightVolk** [comment]
@Eilon , may be! I try to find some tutorial to make my own webhook, but found just this article.

So, i try to add 

`using Microsoft.AspNetCore.WebHooks.Metadata;`

And i have error:Type "WebHooks" does not exists in this namespace.

**Comment by Eilon** [comment]
@LightVolk can you post your project to GitHub so we can take a look? There could be a missing reference or some other error, but we'll need more info to investigate. Thansk!

**Comment by PoojaPadia** [comment]
Any solution for this issue?

**Comment by Lechus** [comment]
these packages are outdated?
Need to grab the source code?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
