### ISSUE TITLE
Is it possible to add the WebHook of Azure DevOps Server?

### ISSUE THREAD

**Issue by Varorbc** [aspnet/AspLabs#186]
Is it possible to add the WebHook of Azure DevOps Server?

**Comment by Eilon** [comment]
Hi @Varorbc , can you provide more details on what you mean by "increase"? Increase what?

**Comment by Varorbc** [comment]
@Eilon sorry, it's an awkward translation.https://github.com/aspnet/AspNetWebHooks/tree/master/src/Microsoft.AspNet.WebHooks.Receivers.VSTS

**Comment by Eilon** [comment]
Hi, you can try using the VSTS hooks but I'm not sure if they're compatible. Otherwise, we don't have plans right now to add any additional support, but you can try adding custom support by using the existing source code as an example.
