### ISSUE TITLE
Every request http://localhost:5050 runs health checks

### ISSUE THREAD

**Issue by lurumad** [aspnet/AspLabs#19]
@damienbod @glennc @JuergenGutsch Every request to http://localhost:5050 runs health checks. I've attached an image that favicon.ico runs health checks (Forget css is a Chrome ext)

![halthchecks](https://cloud.githubusercontent.com/assets/1729519/21003976/77c342b8-bd2e-11e6-926c-5ff83ff75fe7.png)

Also http://localhost:5050/aaa or whatever path you use.

¿What do you think if health check provides a default endpoint (PathString property) and user could configure it?

Greetings Luis.

**Comment by JuergenGutsch** [comment]
You are right. I would prefer to have a separate route (provided by a middleware) for that. Something like http://localhost:5000/healthchecks the same way swashbuckle does it: http://localhost:5000/swagger

**Comment by lurumad** [comment]
Yep,

In my implementation I used a PathString property called EndPoint:

```csharp
public class HealthCheckOptions
{
    public PathString EndPoint { get; set; }

    public IList<HealthCheck> HealthChecks { get; } = new List<HealthCheck>();

    public HealthCheckOptions()
    {
        EndPoint = new PathString("/health");
    }
}
```
and the middleware validates:

```csharp
public async Task Invoke(HttpContext httpContext)
{
    if (httpContext.Request.Path != this.options.EndPoint)
    {
        await next.Invoke(httpContext);
    }
...

Greetings Luis.

**Comment by glennc** [comment]
Yeah, I expect we would end up using path more. Using a separate port was an experiment in this repo because if I wanted to investigate whether it was a good idea to provide the functionality.

**Comment by natemcmaster** [comment]
Closing as this issue is stale. HealthChecks has moved into production. Use https://github.com/aspnet/AspNetCore for issues on this feature in the future.
