### ISSUE TITLE
Channels + ASP.NET

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspLabs#2]
## Channels + ASP.NET

Today our http abstractions expose `Stream` via the `HttpRequest.Body` and `HttpResponse.Body`, until channels has mass adoption and we have enough components that can natively understand them, we **_cannot**_ replace the properties on these types.

With those constraints in mind we need to find a compatible way to introduce these new abstractions. We also want to get raw access to the underlying channels if they exists so there would be no extra wrapping if the pipeline was all channels. In the channels repository, there are extension methods that can convert from Stream to `IReadableChannel`/`IWritableChannel` and vice versa. We would use this technique to "just in time" convert from a `Stream` to a Channel. In Kestrel, we will directly implement `IReadableChannel` on the `FrameRequestStream` and `IWritableChannel` on `FrameResponseStream` (or similar). Code in the middleware pipeline
can then call `HttpRequest.Body.AsReadableChannel()` or `HttpResponse.Body.AsWritableChannel()` to get the underlying channel.

If these extension methods are called on `Stream` implementations that don't implement the `IReadableChannel`, then an implementation wrapping `Stream.CopyToAsync` will be returned. For writes, an implementation of `IWritableChannel` using the a buffer pool would be returned.

With this approach, everything should just work and be as optimal as possible when it can be. It should also be no worse than today when the underlying `Stream` isn't actually a channel.
#### Reading the form body with an IReadableChannel

``` C#
public void Configure(IApplicationBuilder app)
{
  app.Run(async context =>
  {
      var input = context.Request.Body.AsReadableChannel();

      if (!context.Request.HasFormContentType)
      {
          return;
      }
      var formReader = new FormReader();
      while (true)
      {
        var result = await input.ReadAsync();
        var buffer = result.Buffer;

        if (formReader.TryReadForm(ref buffer))
        {
          break;
        }

        if (result.IsCompleted)
        {
           throw new EndOfStreamException("Partial form");
        }

        input.Advance(buffer.Start, buffer.End);
      }
  });
}
```
#### Writing a response using an IWritableChannel

``` C#
public void Configure(IApplicationBuilder app)
{
  app.Run(async context =>
  {
      // Under the covers, this is how we would implement Response.WriteAsync(string)
      var output = context.Response.Body.AsWritableChannel();

      // Lease memory directly from the Kestrel pool and write into the buffer
      output.WriteUtf8String("Hello World");

      // Tell Kestrel to look at the data
      await output.FlushAsync();
  });
}
```
#### Middleware wrapping the response output in a MemoryStream

``` C#
public void Configure(IApplicationBuilder app)
{
  // Unfortunately, people sometimes buffer the ENTIRE response body to a MemoryStream
  // it's suboptimal but still needs to work.
  app.Use(async (next, context) =>
  {
      var ms = new MemoryStream();
      var previous = context.Response.Body;
      try 
      {
        context.Response.Body = ms;
        await next();
        ms.Position = 0;
        await ms.CopyToAsync(previous);
      }
      finally 
      {
        context.Response.Body = previous;
      }
  });

  app.Run(async context =>
  {
     var output = context.Response.Body.AsWritableChannel();
     var buffer = output.Alloc();
     buffer.WriteUtf8String("I can write data just fine to the memory stream but it's inefficient :(");
     await buffer.FlushAsync();
  });
}
```
#### Reading part of the request body as a channel and reading the rest as a stream

``` C#
public void Configure(IApplicationBuilder app)
{
  // The content length is 50
  app.Use(async (next, context) =>
  {
      var input = context.Request.Body.AsReadableChannel();
      // Read 25 bytes and call the next middleware
      var result = await input.ReadAsync();
      var buffer = result.Buffer.Slice(0, 25);
      input.Advance(buffer.End);
      await next()
  });

  app.Run(async context =>
  {
        // Read the remaining 25
        byte[] data = new byte[25];
        await context.Request.Body.ReadAsync(data);
  });
}
```
### Open issues
- We need to make sure the performance of the non-Channel implementing `Stream` is on par with using Stream directly.
- We need to make sure we don't allocate a new channel per request (Kestrel pools Streams). We want the lifetime to match the underlying
  stream's lifetime where possible.
- If you write to or read from the underlying channel and then the backing `Stream` it should work (and vice versa).
### Future
- Deprecate Stream properties?
- Expose Channel properties directly on the `HttpReqest`/`HttpResponse` objects?

**Comment by aL3891** [comment]
re: that last point, what would happen if a middleware reads from the body using the channel and another later middleware after that reads using the stream, would that cause issues? Maybe its fine as long as the first middleware makes sure to call `Advance()` and the stream implementation updates its position. (can you call advance with only part of the buffer?)

**Comment by davidfowl** [comment]
That would be a good sample to add. 

```C#
var channel = context.Request.Body.AsReadableChannel();
var buffer = await channel.ReadAsync();
channel.Advance(buffer.End);

var data = new byte[2048];
await context.Request.Body.ReadAsync(data);
```

If you do this, it would work fine if the backing stream was a channel. The first read would give you some data, then the next actual stream read would still work.

If the stream wasn't backed by a channel and the wrapping channel did `CopyToAsync` it would be broken. The `CopyToAsync` operation would be running and the `ReadAsync` would probably just not work or give you the wrong data. It's possible we might need to pass a flag to `AsReadableChannel` that lets you take over the entire stream. That way, you could choose whether you want to allow more data to be read after you stop reading from the channel and read from the underlying `Stream` after the fact.

**Comment by halter73** [comment]
@aL3891 Do you have any examples of any middleware that reads just part of the request body and then leaves the request stream in place without wrapping or replacing it?

How would the first middleware reading from the request stream avoid potentially overreading? I guess it's possible that the middleware could know exactly how many bytes it needs to read in advance, but I'm not sure of a scenario where that would be the case. I think in the rare case that you have different middleware reading different parts of the request body, all the middleware should be using the same abstraction. There's also the option of buffering with MemoryStream and replacing the request body with that.

**Comment by aL3891** [comment]
@halter73 well no not really in practice.. One example might be reading image metadata or if someone has some custom message dispatching or something. But given that its such a general mechanism I just think its a case that should be considered, as David said, it should be predictable 

Maybe its enough to just throw an exception in those cases. I don't think people would really do this on purpose but suppose someone uses different external middlewares, They might not know if each middleware uses streams or channels, so they might end up with a mix. Maybe the way to solve for those cases (where you cant add buffering yourself) is to have like a buffering middleware that you put first

That's my point really, that people might use external middleware that they a) can't change (like add buffering) and b) don't know if it uses streams of channels

**Comment by natemcmaster** [comment]
Closing as this experiment has moved into production as System.IO.Pipelines. See https://blogs.msdn.microsoft.com/dotnet/2018/07/09/system-io-pipelines-high-performance-io-in-net/
