### ISSUE TITLE
Healthcheck project

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/AspLabs#20]
I had worked on healthcheck on my own side without seen the work done here. 
The code is just commited here : https://github.com/ycrumeyrolle/HealthCheck/tree/dev

The goal is to provide an endpoint for HTTP load balancer health check and to provide an endpoint health status of the application.
For example, the /ping endpoint simply returns 200 of 502 HTTP status based on server maintenance state and the critical dependencies
The /health endpoint returns JSON representation of the application heath, like external dependencies health, server health, application errors, ...

Features :
- [x] Return 200 when the server is OK
- [x] Return 503 when the application on the server is in maintenance mode (based on server toggle)
- [x] Return 503 when the application has a critical health check failure
- [x]  Return JSON representation of  the health status of the application
  - [x] Measure health check elapsed time
  - [x] Distinguish critical versus informational health check
  - [x] Allow multiples tags on  health check
  - [x] Each health check may have a specific retry delay (none for memory check, once per minute for http service, ...)
- [x] Provide health check
  - [x] Process related health check (memory, disk space, ...)
  - [x] HTTP endpoint health check
  - [x] EF health check
  - [x] Certificate health check
  - [x] Counter-based health check (for example based on exceptions count)
- [ ] Health service could be used for feature flipping, ie. disable a payment feature if the payment service is unhealthy 

Could you take a look ? @glennc @damienbod

**Comment by damienbod** [comment]
@ycrumeyrolle cool project, really cool stuff.

@glennc @anurse @davidfowl  @lurumad @JuergenGutsch We now have 3 good projects for health checks with some cool ideas.

If you want, we could create an ASP.NET health check github group and implement this feature for you with your guidance, then you don't need to implement it yourself. Or we wait and contribute to your new repo.

 What do you think?

Greetings Damien

**Comment by alhardy** [comment]
Looks like this come from [Metrics.Net](https://github.com/etishor/Metrics.NET) :)

I've [ported](https://github.com/alhardy/AppMetrics/tree/1.0.0) to dotnet core after trying to get commitment to support dotnet core with no luck.

https://alhardy.github.io/app-metrics-docs/getting-started/health-checks/index.html#configuring-health-checks

**Comment by glennc** [comment]
We moved the code we have here over to github.com/aspnet/HealthChecks

**Comment by natemcmaster** [comment]
Closing as this issue is stale. HealthChecks has moved into production. Use https://github.com/aspnet/AspNetCore for issues on this feature in the future.
