### ISSUE TITLE
Looking for advice on referencing the Proxy project & license 

### ISSUE THREAD

**Issue by BasHamer** [aspnet/AspLabs#206]
I grabbed the proxy code a few years back and build an on-demand short-lived proxy service on it.

I'm getting to the point where I need to start versioning it, and I want to make sure my license, reference  etc. is set up right; I'd also like to know if there is a preferred way to reference this code (I copied it into my own repo, works for me, not sure if it is the preferred way) 

Do I need to add the license & notice reference on the Docker image distribution?

For the project: https://github.com/BasHamer/Slipka

It is mostly used in docker to work with a selenium grid; each browser gets its own proxy for a test and we use the proxy to find error codes, grab intercepted files (downloaded reports) etc. 

For a set of features: https://github.com/BasHamer/Slipka/tree/master/Slipka.Test/Features

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
