### ISSUE TITLE
Proxy configured with asp.net core 2.2 with full framework 4.6.1 returns  "Your POST request is not being received quickly enough. Please retry"

### ISSUE THREAD

**Issue by sanjaycedti** [aspnet/AspLabs#215]
In order to call some APIs which do not support cors, we configured a proxy (using [AspLabs Proxy](https://github.com/aspnet/AspLabs/tree/master/src/Proxy)) in an existing asp.net  core 2.2 with framework 4.6.1. Calling those APIs through this proxy results in `408` with message `Your POST request is not being received quickly enough. Please retry.`. But it perfectly works fine with the proxy configured with asp.net core 2.2. It also works fine with rest clients (e.g., postman) and browsers. Here is the code. Thanks for your help in advance.

```
public void ConfigureServices(IServiceCollection services)
{
	...
	services.AddProxy(options =>
	{
		options.MessageHandler = new HttpClientHandler
		{
			AllowAutoRedirect = false,
			UseCookies = true
		};
	});

	services.AddMvc(...).SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        ...
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
	...
	app.UseWebSockets()
		.Map("/auth-proxy", api => api.RunProxy(new Uri("https://auth.example.com")));

	...
}
```

**Comment by sanjaycedti** [comment]
Turned out it is not related to the proxy, a simple `HttpClient` also has the same issue with .net core 2.x with framework 4.6.1. Here is the code snippet I tried - 

```
using (var client = _httpClientFactory.CreateClient())
{
	client.BaseAddress = new Uri(requestUri);
	var response = await client.PostAsync(string.Empty, new JsonContent(data));
	var content = await response.Content.ReadAsStringAsync();
	return StatusCode((int)response.StatusCode, content);
}
```

**Comment by sanjaycedti** [comment]
Any update on this as I'm still struggling for the solution.

**Comment by johnib** [comment]
any update on this @sanjaycedti ?

**Comment by sanjaycedti** [comment]
> any update on this @sanjaycedti ?

I migrated the code to .net core 2.x (pure .net core without .net framework) to make it work.

**Comment by davidfowl** [comment]
All proxy work has moved to https://github.com/microsoft/reverse-proxy.
