### ISSUE TITLE
open in VS 2019

### ISSUE THREAD

**Issue by FrkatSmrkat** [aspnet/AspLabs#220]
when i try to open the .sln in VS 2019 none of the projects loads.
can you pls add some startvs.cmd as there is in https://github.com/aspnet/Extensions
or whatever is needed so anyone can open the .sln without finding out why it isnt so simple?
Thanks regards

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
