### ISSUE TITLE
services.AddProtectedBrowserStorage(); return error.

### ISSUE THREAD

**Issue by ahmeddawood88** [aspnet/AspLabs#222]
when i inserted this line of code

services.AddProtectedBrowserStorage();

into Startup.cs file of my Blazor app, I got this error:
iservicecollection does not contain a definition for addprotectedbrowserstorage.

I followed exactly what MS document instructed to work on Session management of Blazor App:
https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.0

Any help is appreciated
Thanks

**Comment by kblood** [comment]
I am having the same problem. I noticed this at the top of the page:
"Blazor Server is supported in ASP.NET Core 3.0. Blazor WebAssembly is in preview for ASP.NET Core 3.1."

Maybe this feature is only supported by .Net Core 3.1?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
