### ISSUE TITLE
IE 11 bug - Arrow Function not supported!

### ISSUE THREAD

**Issue by maxxintegration** [aspnet/AspLabs#234]
IE 11 does not support "Arrow Function" therefore the following code block in "_content/Microsoft.AspNetCore.ProtectedBrowserStorage/protectedBrowserStorage.js" file will not work.

<script src="_content/Microsoft.AspNetCore.ProtectedBrowserStorage/protectedBrowserStorage.js"></script>

(function () {
    // We may be able to eliminate this .js file entirely as of preview 8,
    // because it will be possible to invoke things like localStorage.setValue
    // directly from .NET without needing a JS wrapper
    window.protectedBrowserStorage = {
        get: (storeName, key) => window[storeName][key],
        set: (storeName, key, value) => { window[storeName][key] = value; },
        delete: (storeName, key) => { delete window[storeName][key]; }
    };
})();

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
