### ISSUE TITLE
webhooks - allow for PUT method?

### ISSUE THREAD

**Issue by Lechus** [aspnet/AspLabs#237]
I got one webhook provider client and they do PUT instead of POST.
Is the allow POST only webhook standard or not?
Could WebHookVerifyMethodFilter be extender to allow other  PUT method? like in
```
MyWebhookMetadata {
public override IsPutAllowed = true; 
}
```

?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
