### ISSUE TITLE
DeleteAsync doesn't appear to work

### ISSUE THREAD

**Issue by DataJuggler** [aspnet/AspLabs#246]
I am implementing my own sign in / sign out and it works great where I store a password hash locally to save the user typing in a user name password every time.

I call a method to remove the local storage items if they chose not to remember password.

After this call successfully runs (no errors are thrown and the code exits this method).

                try
                {
                    // if the ProtectedLocalStore exists
                    if (ProtectedLocalStore != null)
                    {
                        // Remove all items
                        await ProtectedLocalStore.DeleteAsync("RememberPassword");
                        await ProtectedLocalStore.DeleteAsync("ArtistEmailAddress");
                        await ProtectedLocalStore.DeleteAsync("ArtistPasswordHash");
                    }
                }
                catch (Exception error)
                {   
                    // for debugging only
                    DebugHelper.WriteDebugError("RemoveLocalStoreItems", "Login.cs", error);
                }

The next time the app starts, I still have value of RememberPassword = true.

As a work around, I changed my code to on Sign In if Remember Password is false or Sign Out with option for Remove Saved Password = true, I set Remember Password = false, and the Stored Password Hash and User Name to Empty String and this works to change it, but delete does not seem to work.

Am I doing something wrong? It seems DeleteAsync isn't doing what I expect which is remove the key value pair. 

As a feature request, a DeleteAll method would be preferred way of handling this instead of individual elements.

Thanks, it works great for setting values.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
