### ISSUE TITLE
Update ComponentsElectron to latest blazor preview relase

### ISSUE THREAD

**Issue by GoranHalvarsson** [aspnet/AspLabs#250]
Please update ComponentsElectron to current blazor preview.
Because of breaking changes in the preview 3.2.0-preview1.20073.1.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
