### ISSUE TITLE
Microsoft.AspNetCore.Grpc.HttpApi doesn't return the status set in the handler

### ISSUE THREAD

**Issue by mijgame** [aspnet/AspLabs#263]
Hi!

I was trying out the Microsoft.AspNetCore.Grpc.HttpApi package to map Grpc calls to HTTP. 
One of the things I'm running into, is that statusses (such as `StatusCode.InvalidArgument`) are not passed through to the REST client.

The `HandleCallAsync` function in the `UnaryServerCallHandler` basically does nothing with the status in the `ServerCallContext`.

Are there any plans on adding this functionality? Right now, there is basically no good way to send error information to clients, aside from adding error information into the grpc messages themselves.

Thanks in advance.

**Comment by JamesNK** [comment]
Fixed. gRPC status codes now map to HTTP status codes. Logic matches what grpc-gateway does here.
