### ISSUE TITLE
Interceptors don't work with HttpApi

### ISSUE THREAD

**Issue by albertyfwu** [aspnet/AspLabs#270]
Previously, in my gRPC project, I had gRPC interceptors for logging and exception wrapping.

Now, after adding `GrpcHttpApi`, whenever I get an inbound request, I get `System.InvalidOperationException: 'Could not get HttpContext from ServerCallContext. HttpContext can only be accessed when gRPC services are hosted by Kestrel.'` in `Grpc.Shared.Server.InterceptorPipelineBuilder.cs`.

Is it possible to expose the `HttpContext`?

**Comment by albertyfwu** [comment]
I'm actually pretty confused why it's not working...

Exception is generated here:
https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.AspNetCore.Server/ServerCallContextExtensions.cs#L64

That means that `serverCallContext.UserState` was probably `null` or the `__HttpContext` key didn't exist in it.

But `.UserState => UserStateCore` in https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core.Api/ServerCallContext.cs

and `UserStateCore => _httpContext.Items` in https://github.com/aspnet/AspLabs/blob/058908b38ba7072b22044ac8bed8e1fd4647d219/src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/HttpApiServerCallContext.cs

which is populated at https://github.com/aspnet/AspLabs/blob/058908b38ba7072b22044ac8bed8e1fd4647d219/src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/HttpApiServerCallContext.cs#L28

**Comment by albertyfwu** [comment]
Never mind. The change was made [here](https://github.com/grpc/grpc-dotnet/commit/afc2b217619e9f96e3de3be2dfce650a9468939c) and it's not in the latest version of `Grpc.AspNetCore` yet. How can I get access to this other than compiling from source?

**Comment by JamesNK** [comment]
It is available now from the nightly build feed.

https://github.com/aspnet/AspLabs/tree/master/src/GrpcHttpApi#nuget-feed

**Comment by albertyfwu** [comment]
Thanks!

**Comment by albertyfwu** [comment]
@JamesNK I just double-checked, and the change is in `Grpc.AspNetCore`, not `GrpcHttpApi`.
