### ISSUE TITLE
GrpcHttpApi missing descriptor.proto file

### ISSUE THREAD

**Issue by krigol** [aspnet/AspLabs#273]
Hello, so I'm trying to use the GrpcHttpApi along with Grpc Swagger. The Sample uploaded in the project works perfect, but when I try to reproduce it in my own project, follow the steps, the `google/api/annotations.proto` file says it's missing `google/protobuf/descriptor.proto`. I looked for it in your Sample project for referance, but it wasn't there. From a `grep 'descriptor.proto' -r` scan I noticed it comes from Grpc.Tools NuGet, but I have that as well. It's even a newer version (2.28.1). Yes, I also tried matching versions (2.27.0), but nothing works. I also tried finding it manually, but the one online seems to be for "proto2" syntax which is incompatible with the `google/api/annotations.proto` file.
![image](https://user-images.githubusercontent.com/19262363/79421695-05739580-7fc4-11ea-9a87-8f9bfda7a7bd.png)

**Comment by davidfowl** [comment]
cc @JamesNK

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
