### ISSUE TITLE
GrpcHttpApi for .NET Core 3.1

### ISSUE THREAD

**Issue by alejandrobonillamondragon** [aspnet/AspLabs#284]
I was able to run the example provided for .NET Core 3.0 and it's exactly what I was looking for, however, it doesn't work for 3.1 and I cannot downgrade to 3.0. Any plan to support 3.1?

**Comment by JamesNK** [comment]
It works in 3.1 - https://github.com/aspnet/AspLabs/tree/master/src/GrpcHttpApi/sample
