### ISSUE TITLE
Please publish to Nuget Gallery

### ISSUE THREAD

**Issue by sk6868** [aspnet/AspLabs#286]
Hello,

I know this code is not yet in production, but it would be great if it were published as a NuGet package.  Are there are any plans to do so in the near future?

**Comment by Curtis-** [comment]
> Hello,
> 
> I know this code is not yet in production, but it would be great if it were published as a NuGet package. Are there are any plans to do so in the near future?

They already have:
https://www.nuget.org/packages/Microsoft.AspNetCore.ProtectedBrowserStorage

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
