### ISSUE TITLE
ProtectedBrowserStorage IndexDB protection

### ISSUE THREAD

**Issue by VenkateshSrini** [aspnet/AspLabs#296]
Hi,
Though this library has a well-defined goal of protecting the content in local storage, can the same mechanism be extended to handle content for IndexDB also? This will be useful in the progressive Blazor app. We can use the IndexDB persistence as an offline store and maybe sync when the network is online again.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
