### ISSUE TITLE
Add CI for this repo

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AspLabs#31]
Add an Azure DevOps build definition to produce builds for PRs and commits.

**Comment by natemcmaster** [comment]
cc @Eilon @anurse what do you think about having this repo also produce packages on a public feed?

**Comment by anurse** [comment]
Yeah, we'll want to produce signed tools packages for `dotnet-monitor` and get them up on a public MyGet

**Comment by Eilon** [comment]
I'm OK with it. @DamianEdwards any concerns? Presumably everything here would be permanently in pre-release. Only if something makes it out into a "regular" repo it would have a chance at RTM?

**Comment by natemcmaster** [comment]
This was done at some point.
