### ISSUE TITLE
Status question

### ISSUE THREAD

**Issue by NedDerick** [aspnet/AspLabs#354]
Hi guys,

Is the grpcHttpApi project still alive or is the recommendation still to use the "generator" approach at this stage? 

We have multiple REST API's that we want to migrate to gRPC, but we need to keep supporting REST for the time being. This looks like a perfect solution for what we need. I don't mind using experimental code, as long as it will be supported in future, but I don't see a commitment to this project as yet? 

Thanks,
D

**Comment by BrennanConroy** [comment]
As long as it is in this repo it is not supported and the future is unknown for it.
