### ISSUE TITLE
Bug: headManager.js fails to inject when Blazer base href modified.

### ISSUE THREAD

**Issue by bradbamford** [aspnet/AspLabs#356]
I'm using a base url for Blazor, and 

**Error:** 
Failed to fetch dynamically imported module: https://localhost:5001/blazor/_content/Microsoft.AspNetCore.Components.Web.Extensions/headManager.js

**_Host.cshtml contains:**
`<base href="~/blazor/" />`
...
`<script src="~/_framework/blazor.server.js"></script> `
`<script src="~/_content/Microsoft.AspNetCore.Components.Web.Extensions/headManager.js"></script>`

blazor.server.js is loaded properly, but headManager.js doesn't respect the ~/ root link. 
headManager.js always tries to concat the blazor root href, resulting in the error above because it is trying to add **/blazor/** to the path.

**Comment by MackinnonBuck** [comment]
We are introducing a new way to modify the HTML head from Blazor, which will hopefully be available in preview7 (or rc1 at the latest). It will not require an additional JS file as `Components.Web.Extensions` did, so this problem will naturally go away.
