### ISSUE TITLE
GrpcHttpApi Exceptions Not getting Logged

### ISSUE THREAD

**Issue by BaleCR7** [aspnet/AspLabs#363]
Hi,

I may have missed something, but I don't seem to see exceptions that are being thrown by our Controller being logged on the Server when making HTTP/Rest calls. I do see the exceptions being logged when making grpc calls.

**Comment by JamesNK** [comment]
If that is happening then it is a bug that should be fixed.

Error conditions are a place where there hasn't been much testing in GrpcHttpApi.

**Comment by BrennanConroy** [comment]
This issue was moved to dotnet/aspnetcore#34523
