### ISSUE TITLE
[Question] On the future of Components.Web.Extensions

### ISSUE THREAD

**Issue by thepra** [aspnet/AspLabs#364]
It's been many months(7-8) the last time that that project saw any update and I do run this library in production(SEO titles are important for me).

Is there any plan for this "experiment" going forward and see a production ready release? 
Or should I just leave it and rely on our own implementation for changing the title or other things that this library enables?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We've productized this as part of the work in the dotnet/aspnetcore repo: https://github.com/dotnet/aspnetcore/issues/25705
It will ship in the upcoming 6.0-preview7 release.
