### ISSUE TITLE
Microsoft.AspNetCore.Components.Web.Extensions Title headManager.js Uncaught SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by groogiam** [aspnet/AspLabs#365]
Microsoft.AspNetCore.Components.Web.Extensions headmanager.js causes the following error when using the <Title> component.

![image](https://user-images.githubusercontent.com/1992395/118301334-edb15e00-b4b0-11eb-8789-b2b6c9326c57.png)

**Comment by ZyuanC** [comment]
I am afraid you did not specify the type of the referenced <script> tag in the index.html. Load it in "module" type explicitly, you can try this

<script src="_content/Microsoft.AspNetCore.Components.Web.Extensions/headManager.js" type="module"></script>
