### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#37]
_From @ankitbko on Thursday, August 30, 2018 9:30:05 PM_

Is this still being developed? Do we have a timeline or roadmap for this?

I am currently using myget feed, have we published this to nuget.org as well?

_Copied from original issue: aspnet/WebHooks#325_

**Comment by aspnet-hello** [comment]
_From @Eilon on Monday, September 10, 2018 10:22:31 AM_

@danroth27 can you provide the latest info?

**Comment by aspnet-hello** [comment]
_From @ankitbko on Monday, September 17, 2018 7:59:10 PM_

Any update on this?

**Comment by mkArtakMSFT** [comment]
Work on ASP.NET Core Web Hooks is not a priority for us at this time. There are no planned updates or releases.
