### ISSUE TITLE
ASP.NET Core WebHooks moved out of ASP.NET Core 2.1

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#38]
_From @danroth27 on Friday, May 4, 2018 2:55:37 PM_

Discussion for https://github.com/aspnet/Announcements/issues/299

------

We are moving ASP.NET Core WebHooks out of the ASP.NET Core 2.1 to give more time to validate the design and implementation. We will continue to ship previews ASP.NET Core WebHooks packages, but they not ship as stable packages as part of the ASP.NET Core 2.1 release.

### Why?

[ASP.NET Core WebHooks](https://github.com/aspnet/webhooks) is only a partial port of [ASP.NET WebHooks](https://github.com/aspnet/aspnetwebhooks) and hasn't received sufficient attention during the ASP.NET Core 2.1 release for us to feel comfortable shipping it at this time. 

_Copied from original issue: aspnet/WebHooks#296_

**Comment by aspnet-hello** [comment]
_From @WestDiscGolf on Wednesday, May 9, 2018 12:42:49 PM_

Thanks for the update @danroth27. I can't deny I'm a little disappointed to hear this but completely understand the reasoning. It's better to have good quality than ship something early and not be happy with it :-)

I have been working on [my own webhook](https://github.com/WestDiscGolf/Fitbit.Net-Webhook) which I will update with the latest preview packages as they come.

Will there be opportunity for more community contributions to the webhook library now it's not on the 2.1 train?

Cheers

**Comment by aspnet-hello** [comment]
_From @tpeczek on Wednesday, May 30, 2018 11:38:29 AM_

Is there a plan to make 1.0.0-preview3-final available on NuGet? Currently it's only on MyGet.

**Comment by aspnet-hello** [comment]
_From @WestDiscGolf on Wednesday, May 30, 2018 11:42:18 AM_

@tpeczek none of the others, AFAIK, have been put on nuget so doubt it. I had to add the myget feed for my Webhook. Hoping more info in the 2.2 time frame will come out soon :-)

**Comment by aspnet-hello** [comment]
_From @tpeczek on Wednesday, May 30, 2018 11:48:04 AM_

@WestDiscGolf 1.0.0-preview1-final and 1.0.0-preview2-final are on NuGet and you can use them. I'm also using MyGet rigth now, but with ASP.NET Core 2.1.0 RTM out I was hoping to switch my project back to NuGet. The only thing stopping me is absence of 1.0.0-preview3-final.

**Comment by aspnet-hello** [comment]
_From @WestDiscGolf on Wednesday, May 30, 2018 11:50:38 AM_

@tpeczek ah cool. Dont think I realised. When it was dropped from the 2.1 timeframe other stuff, both tech and personal, got in the way. Hope to pick it back up again once more info on 2.2 is released.

**Comment by aspnet-hello** [comment]
_From @WestDiscGolf on Saturday, June 2, 2018 12:14:38 PM_

@tpeczek Just checked and 1.0.0-preview3-final isn't on myget anymore :-(

@danroth27 / @dougbu Any update on 1.0.0-preview3-final on nuget?

**Comment by aspnet-hello** [comment]
_From @tpeczek on Saturday, June 2, 2018 1:27:05 PM_

@WestDiscGolf It looks like it's still there: https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.AspNetCore.WebHooks.Receivers/1.0.0-preview3-final

**Comment by aspnet-hello** [comment]
_From @WestDiscGolf on Saturday, June 2, 2018 1:29:11 PM_

@tpeczek Thanks for that. I thought I'd tried that but must have missed typed it :-)

**Comment by aspnet-hello** [comment]
_From @vankampenp on Monday, July 16, 2018 1:08:20 AM_

What is the best place to discuss the functionality of webhooks in 2.x?
I am missing a way to create a custom webhook, or at least lack the understanding how to do that :-)
There were two webhook consumers that I would like to integrate, but each are different from the once that are provided. For example WooCommerce on Wordpress uses JSON, so it is not compatible with the Wordpress webhook.

**Comment by aspnet-hello** [comment]
_From @tpeczek on Monday, July 16, 2018 1:17:38 AM_

@vankampenp 

If what you are really looking for is creating your own custom webhook receiver you may find my blog series useful: [Under the hood of ASP.NET Core WebHooks](https://www.tpeczek.com/2018/05/under-hood-of-aspnet-core-webhooks.html)

You may also want to take a look at coupel early custom receivers implementations:
- [Fitbit.Net-Webhook](https://github.com/WestDiscGolf/Fitbit.Net-Webhook)
- [WebSub.NET](https://github.com/tpeczek/WebSub.NET/tree/master/src/WebSub.AspNetCore.WebHooks.Receivers.Subscriber)

**Comment by aspnet-hello** [comment]
_From @WestDiscGolf on Monday, July 16, 2018 1:30:55 AM_

@vankampenp I documented my investigation of the the early webhooks and writing the fitbit one. Check out [my blog series](https://adamstorr.azurewebsites.net/blog/aspnetcore-webhooks-mini-series). Hope this helps.

**Comment by aspnet-hello** [comment]
_From @vankampenp on Thursday, July 26, 2018 6:49:15 AM_

@tpeczek and @WestDiscGolf, thanks these are useful. I had hoped to get an example that shows how to override some methods to allow you to customize the webhook, rather than changing the available source. But maybe this is the root. I will post an issue.

**Comment by aspnet-hello** [comment]
_From @lsuarez5280 on Tuesday, August 28, 2018 10:16:25 AM_

Since this is also going to miss the 2.2 milestone, do we know where this is going to fall on the roadmap? This is seconds from being pushed over the finish line and I'd like to update our existing custom Framework-based webhook receivers to this library.

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, August 28, 2018 10:30:26 AM_

@danroth27 / @DamianEdwards - do we have an updated roadmap for this?

**Comment by aspnet-hello** [comment]
_From @WestDiscGolf on Tuesday, August 28, 2018 10:33:14 AM_

I can't help but feel this is going to wait for the new fully opened End Point Routing middleware coming in v3. I just feel like with the clashing of the apicontroller attribute work and the hard coded routing in the webhooks it makes sense that it will use the new middleware when it arrives

**Comment by aspnet-hello** [comment]
_From @usaadi on Wednesday, October 10, 2018 3:04:37 PM_

Is there an available preview for custom webhook sender on myget or elsewhere?

**Comment by aspnet-hello** [comment]
_From @dougbu on Wednesday, October 10, 2018 3:13:04 PM_

@usaadi not something built in this repo. Others may certainly have forked the code and implemented sender support.

If you want sender support in general, the other option is to use Microsoft.AspNet.WebHooks.Custom and related packages. Those are available on NuGet.org. Slightly newer versions are available in the https://dotnet.myget.org/gallery/aspnetwebhooks feed.

**Comment by aspnet-hello** [comment]
_From @SeanFarrow on Thursday, October 11, 2018 11:03:30 PM_

Given that this project has been moved to asplabs, where should we raise issues/questions?

**Comment by aspnet-hello** [comment]
_From @WestDiscGolf on Thursday, October 11, 2018 11:05:59 PM_

Moving to asplabs is both disappointing and confusing :-(

**Comment by Misiu** [comment]
Any updates on WebHooks? Will it be added to .NET Core 3.0? All packages are in preview.
Can someone share plans regarding webhooks?

**Comment by danroth27** [comment]
@Misiu WebHooks is not shipping with .NET Core, and there is no roadmap to ship WebHooks at this time.

**Comment by Misiu** [comment]
@danroth27 sad to read that.
I must search for an alternative then.

Is there a place we can vote for features like WebHooks to be added to the roadmap?

**Comment by danroth27** [comment]
@Misiu You can always submit feedback on ASP.NET Core by opening issues on the https://github.com/aspnet/aspnetcore repo. However, at this point we consider support for WebHooks to be out of scope. We are considering working with the community to find a new owner for this project for folks that want to see it carried forward.

**Comment by mguinness** [comment]
@danroth27 Any chance the decision to not to ship WebHooks could be reconsidered?  I just created a package for [Webhook support for Box](https://github.com/mguinness/BoxWebHook) and it works well.

What's the developer story using ASP.NET Core 3.0 and webhooks?  Seems like a common use case that isn't getting much attention from Microsoft or the community.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this project is in maintenance mode and only critical security issues are being considered.
