### ISSUE TITLE
Please add support for the Vend API

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#41]
_From @Yusha813 on Monday, April 23, 2018 7:52:22 AM_

Hello, I am trying to use the WebHooks feature to receive posts from the [Vend API](https://docs.vendhq.com/docs/webhooks). Please add a NuGet package for this.

_Copied from original issue: aspnet/WebHooks#289_

**Comment by aspnet-hello** [comment]
_From @dougbu on Tuesday, April 24, 2018 2:38:15 PM_

@Yusha813 we've moved this issue is in the Backlog milestone. This means that it is not going to happen for the coming release. We will review the backlog and consider this ask in the future.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this project is in maintenance mode and only critical security issues are being considered.
