### ISSUE TITLE
Detect more `[WebHook]` conflicts with other attributes

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#42]
_From @dougbu on Monday, March 26, 2018 9:56:47 PM_

Splitting out from #248 (see [this comment](https://github.com/aspnet/WebHooks/issues/248#issuecomment-373820480)):
> `WebHookRoutingProvider` doesn't actually `throw` in all attribute routed cases, only when an attribute route on an action provides a `Template`. Should check the `ControllerModel` for an attribute route and check both WebHook actions and containing controllers for an `HttpMethodActionConstraint` i.e. the result of an applied `IActionHttpMethodProvider` (see `DefaultApplicationModelProvider`).

> Should probably also check for `IConsumesActionConstraint`s since `[Consumes]` interferes with `WebHookEventNamesConstraint`s and `WebHookVerifyBodyTypeFilter`s.

Suggest doing this work post-Preview2. Basically about clarifying error messages in problematic cases.

_Copied from original issue: aspnet/WebHooks#269_

**Comment by aspnet-hello** [comment]
_From @dougbu on Tuesday, April 10, 2018 12:48:30 PM_

Clearing the milestone. Need to discuss whether to address #248 or this issue during RC1.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this project is in maintenance mode and only critical security issues are being considered.
