### ISSUE TITLE
`X-Hook-UUID` does not exist for Bitbucket Server, but is required for the webhook receiver

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#44]
_From @forrestab on Wednesday, February 14, 2018 11:07:29 AM_

### Functional impact

Because the `X-Hook-UUID` does not exist in webhook requests from Bitbucket Server, the error "A 'bitbucket' WebHook request must contain a 'X-Hook-UUID' HTTP header." is thrown and the webhook handler is never executed.

### Minimal repro steps

1. Run a local Bitbucket Server 5.7.1 (I am using docker)
2. Create a test repo and add a webhook (for me I am trying to hook into `pr:opened`)
3. Make sure your handler is started
4. Perform action in Bitbucket server that executes the webhook (in my case opening/re-opening a pull request)
5. Go to the webhook event log to see the response (test repo -> Repository settings -> WebHooks -> View details (next to your webhook)) in the "Last failure" column

If it helps here is the code I am using as the receiver, https://github.com/forrestab/bitbucket-server-webhooks.

### Expected result

Expected the handler to be called with the correct hook data.

### Actual result

Exception is thrown and the handler is never called.

### Further technical details

I don't understand the reasoning, but webhook requests from [Bitbucket Server](https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html#Eventpayload-httpheadersHTTPheaders) contain slightly different headers than [Bitbucket Cloud](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-HTTPheaders).

Also, based on the HTTP headers listed for Bitbucket Server, there does not appear to be a matching `X-Hook-UUID`. Would it be possible to disable this check?

_Copied from original issue: aspnet/WebHooks#249_

**Comment by aspnet-hello** [comment]
_From @mkArtakMSFT on Friday, February 16, 2018 9:52:08 AM_

Thank you for reporting this issue. @dougbu, can you please look into this? Thanks!

**Comment by aspnet-hello** [comment]
_From @dougbu on Saturday, February 17, 2018 9:34:00 PM_

@forrestab we've moved this issue is in the Backlog milestone. This means that it is not going to happen for the coming release.

Have also marked this issue as up-for-grabs. This means we will review a PR filling this gap if someone submits one.

By "this gap" I mean interoperability with Bitbucket Server, not just a new option to disable the `X-Hook-UUID` requirement. We do not have a Bitbucket Server instance to test against. Nor do we have any confidence the missing `X-Hook-UUID` header is the only Bitbucket Cloud / Server difference.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this project is in maintenance mode and only critical security issues are being considered.
