### ISSUE TITLE
WebHookSecurityFilter should use `DefaultIdConfigurationKey` in log when id is null or empty

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#46]
_From @pranavkm on Thursday, February 8, 2018 4:18:40 PM_

https://github.com/aspnet/WebHooks/blob/a05a07c420e6316963f41d7bad3fc38e6b74464c/src/Microsoft.AspNetCore.WebHooks.Receivers/Filters/WebHookSecurityFilter.cs#L288-L292

This prints `Could not find a valid configuration for the 'github' WebHook receiver, instance ''` when the key is invalid.

_Copied from original issue: aspnet/WebHooks#244_

**Comment by aspnet-hello** [comment]
_From @pranavkm on Thursday, February 8, 2018 4:20:00 PM_

Also https://github.com/aspnet/WebHooks/blob/a05a07c420e6316963f41d7bad3fc38e6b74464c/src/Microsoft.AspNetCore.WebHooks.Receivers/Filters/WebHookSecurityFilter.cs#L219-L220

**Comment by aspnet-hello** [comment]
_From @pranavkm on Thursday, February 8, 2018 4:20:47 PM_

Typo: https://github.com/aspnet/WebHooks/blob/a05a07c420e6316963f41d7bad3fc38e6b74464c/src/Microsoft.AspNetCore.WebHooks.Receivers/Filters/WebHookSecurityFilter.cs#L215

**Comment by aspnet-hello** [comment]
_From @Marusyk on Sunday, February 11, 2018 8:12:08 AM_

Hello, do you mean that when the key is invalid should it return other message? I would be glad to fix that if you clarify requirements. Thx

**Comment by aspnet-hello** [comment]
_From @pranavkm on Monday, February 12, 2018 10:13:32 AM_

@Marusyk no, the intent was to use the term "default id" or something along those lines when the key is the default value. Right now it prints empty quotes, which isn't what the user configures in the log. 
Consider

```C#
[GitHubWebHook]
public IActionResult Blah() {..}
```

The log message you see in this case is `Could not find a valid configuration for the 'github' WebHook receiver, instance ''`. Having `''` instance isn't very intuitive. A more appropriate message might be `Could not find a valid configuration for the 'github' WebHook receiver, default instance.`

**Comment by aspnet-hello** [comment]
_From @dougbu on Tuesday, April 10, 2018 12:53:38 PM_

Self-assigning this and two other bugs because we want them done in RC1.

@mkArtakMSFT please add `cost: XS` label in this repo. This issue and #247 fit in that bucket. Perhaps #245 too.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this project is in maintenance mode and only critical security issues are being considered.
