### ISSUE TITLE
Support Azure Activity Log alerts

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#47]
_From @dougbu on Wednesday, December 13, 2017 4:51:49 PM_

The current Azure Alert receivers (ASP.NET and ASP.NET Core) support Azure Metric alerts and (modulo #146) Availability / Web Test alerts. However Activity Log alerts use a completely different JSON schema, one that does not contain the required `context:name` field.

To support Activity Log alerts, update how the Azure Alert receivers find event names. One option is to search the schema for something like an event name (see https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-activity-log-alerts-webhook and linked details e.g. https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-service-notifications). Another option is to fall the event name back to a constant value or to allow the event name to be `null`.

Secondarily, should add strong types per Activity Log alert types e.g. one for Administration alerts and another for Service Health alerts.

_Copied from original issue: aspnet/WebHooks#203_

**Comment by aspnet-hello** [comment]
_From @dougbu on Thursday, December 14, 2017 3:48:29 PM_

https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-activity-log-schema contains more details about the various Activity Log alerts.

**Comment by aspnet-hello** [comment]
_From @aspnet-hello on Monday, March 12, 2018 11:42:07 PM_

This issue was copied to aspnet/AspNetWebHooks#22

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We have no plans to add new features in this area.
