### ISSUE TITLE
Adding a Chargebee receiver

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#50]
_From @fabiodaniele on Sunday, July 23, 2017 2:11:43 PM_

Hi all,
I'd like to contribute to this project by adding a receiver for Chargebee webhooks.

Can I do it? :)

_Copied from original issue: aspnet/WebHooks#147_

**Comment by aspnet-hello** [comment]
_From @garora on Friday, July 28, 2017 2:17:08 PM_

@fabiodaniele - You can create a `PR` as this is an open source you can contribute rest the final decision would be of @HenrikFrystykNielsen

**Comment by aspnet-hello** [comment]
_From @fabiodaniele on Saturday, July 29, 2017 5:17:44 AM_

@garora  - Ok, thanks.

**Comment by aspnet-hello** [comment]
_From @aspnet-hello on Monday, March 12, 2018 11:41:55 PM_

This issue was copied to aspnet/AspNetWebHooks#21

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We have no plans to add new features in this area.
