### ISSUE TITLE
[WebHooks.Receivers.VSTS] WorkItemUpdatedFields is limited to a few predefined system fields

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#51]
_From @NenoLoje on Sunday, June 11, 2017 2:22:10 PM_

This issue is for: **Microsoft.AspNet.WebHooks.Receivers.VSTS**

The [`WorkItemUpdatedFields`](https://github.com/aspnet/WebHooks/blob/master/src/Microsoft.AspNet.WebHooks.Receivers.VSTS/Payloads/WorkItemUpdatedFields.cs) class has **9** fields defined.

VSTS offers many more fields (system and custom ones) that could be part of this event as well. This does not seem to be implemented currently.

Questions:

1. How can I access other **custom fields**? Any plans to extend this class?
2. Would you be **willing to accept PRs** for other built-in system fields (like `System.IterationPath``)?

Thanks,
--Neno

_Copied from original issue: aspnet/WebHooks#143_

**Comment by aspnet-hello** [comment]
_From @dougbu on Tuesday, November 28, 2017 3:19:54 PM_

Suggest binding to a `JObject` and using the `WebHookReceiverContext` to get that type.

**Comment by aspnet-hello** [comment]
_From @danroth27 on Tuesday, December 12, 2017 3:01:14 PM_

We should look at improving this experience for ASP.NET Core as part of #182

**Comment by aspnet-hello** [comment]
_From @dougbu on Tuesday, January 16, 2018 3:11:50 PM_

Pending work on #182, marking this up-for-grabs and putting it into the Backlog. If someone has VSTS fields e.g. @NenoLoje's `System.IterationPath` they would like to add, send a PR.

**Comment by aspnet-hello** [comment]
_From @aspnet-hello on Monday, March 12, 2018 11:41:41 PM_

This issue was copied to aspnet/AspNetWebHooks#20

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this project is in maintenance mode and only critical security issues are being considered.
