### ISSUE TITLE
can we have one for Sendgrid

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#52]
_From @pooran on Saturday, September 17, 2016 5:13:36 AM_

_Copied from original issue: aspnet/WebHooks#84_

**Comment by aspnet-hello** [comment]
_From @garora on Thursday, September 22, 2016 6:48:43 AM_

@pooran - Have you tried [CustomeReceiver](https://github.com/aspnet/WebHooks/tree/master/samples/CustomReceiver) sample for this.
Documentation for SendGrid WebHooks is avaialble here: [Hooks](https://sendgrid.com/docs/API_Reference/Webhooks/index.html)

**Comment by aspnet-hello** [comment]
_From @SimonLuckenuik on Thursday, April 20, 2017 5:10:29 AM_

I have been using this library for the data contract: https://github.com/mirajavora/sendgrid-webhooks

**Comment by aspnet-hello** [comment]
_From @aspnet-hello on Monday, March 12, 2018 11:41:25 PM_

This issue was copied to aspnet/AspNetWebHooks#19

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. There are no plans to implement any additional web hooks.
