### ISSUE TITLE
Anyone managed to do this with Gmail?

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#53]
_From @georgiosd on Friday, July 29, 2016 1:43:10 AM_

Documentation to set up gmail webhooks is terrible. 

Anyone managed to do this and can give some guidance?

_Copied from original issue: aspnet/WebHooks#77_

**Comment by aspnet-hello** [comment]
_From @HenrikFrystykNielsen on Friday, July 29, 2016 1:16:35 PM_

It's been a while since I looked at gmail webhooks. Do you have a pointer?

**Comment by aspnet-hello** [comment]
_From @georgiosd on Monday, August 1, 2016 9:08:12 AM_

I have made some progress but still not 100% on the workflow. https://developers.google.com/gmail/api/guides/push

**Comment by aspnet-hello** [comment]
_From @aspnet-hello on Monday, March 12, 2018 11:41:11 PM_

This issue was copied to aspnet/AspNetWebHooks#18

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
