### ISSUE TITLE
WebHooks for Office 365

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#54]
_From @rposener on Monday, April 4, 2016 7:37:55 PM_

Saw some of this at build, would be nice if we had a package that would work with the Office 365 WebHooks.  Once the asp.net core port gets a bit further, I will be glad to work on it and submit a pull (for the .net core), but need to figure out an asp.net core port first.

_Copied from original issue: aspnet/WebHooks#51_

**Comment by aspnet-hello** [comment]
_From @aspnet-hello on Monday, March 12, 2018 11:40:57 PM_

This issue was copied to aspnet/AspNetWebHooks#17

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. There are no plans to implement any additional web hooks.
