### ISSUE TITLE
Webhooks support for AWS SNS messages

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#55]
_From @mteper on Tuesday, November 17, 2015 11:51:10 AM_

See http://blogs.aws.amazon.com/php/post/Tx2G9D94IE6KPAY/Receiving-Amazon-SNS-Messages-in-PHP for example of how to handle (example describes PHP but should be pretty straight-forward).

_Copied from original issue: aspnet/WebHooks#28_

**Comment by aspnet-hello** [comment]
_From @aspnet-hello on Monday, March 12, 2018 11:40:46 PM_

This issue was copied to aspnet/AspNetWebHooks#16

**Comment by mguinness** [comment]
This would be a useful receiver to add.  As Amazon SNS sends different types of messages including SubscriptionConfirmation, Notification, and UnsubscribeConfirmation, then it would have to handle verification requests.

Based on the article [Under the hood of ASP.NET Core WebHooks - Verification Requests](https://www.tpeczek.com/2018/06/under-hood-of-aspnet-core-webhooks_21.html), the [Dropbox webhook](https://github.com/aspnet/AspLabs/tree/master/src/WebHooks/samples/DropboxCoreReceiver) code could be used as a starting point.

**Comment by mguinness** [comment]
Amazon SNS receiver is now available at https://github.com/mguinness/SnsWebHook.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. There are no plans to implement any additional WebHooks.
