### ISSUE TITLE
Release Proxy to GA

### ISSUE THREAD

**Issue by Cloudmersive** [aspnet/AspLabs#61]
Why is Proxy not getting released?

**Comment by Eilon** [comment]
Hi @Cloudmersive , the simple answer is that it has not been a high enough priority for the team in comparison to the other features and fixes that we plan to do.

**Comment by damianh** [comment]
Hi, I took the initiative and released my own package forked from here and heavily modified:  https://github.com/damianh/ProxyKit 

@Eilon Hope this is ok, reach out if any concerns. Thx.

**Comment by Eilon** [comment]
@damianh that sounds great, thanks for letting us know! If you'd like, feel free to send a PR to update https://github.com/aspnet/AspLabs/tree/master/src/Proxy with a note at the bottom for "Related projects" that points to your fork. I'd imagine people would find that useful.

**Comment by damianh** [comment]
Thanks for the encouraging response; will do that. Cheers!

**Comment by davidfowl** [comment]
All proxy work has moved to https://github.com/microsoft/reverse-proxy.
