### ISSUE TITLE
Consider delegating dump creation to `procdump`

### ISSUE THREAD

**Issue by anurse** [aspnet/AspLabs#62]
[`procdump` now supports linux](https://github.com/Microsoft/ProcDump-for-Linux)! We could consider either a) delegating dump creation in `dotnet dump` to `procdump` or b) just dropping `dotnet dump` entirely if we think `procdump` provides a sufficient experience.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
