### ISSUE TITLE
Use a matching-architecture process to capture the dump on Windows

### ISSUE THREAD

**Issue by anurse** [aspnet/AspLabs#63]
Via @noafalk: You can get some unfortunate results if you use a 32 bit process to capture a dump of a 64 bit process and vice versa

We don't do anything to protect against this, so if `dotnet dump` moves forward, we should look at spinning off a helper process that matches the bitness.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
