### ISSUE TITLE
ProxyMiddleware Overwrite Exiting Response Headers

### ISSUE THREAD

**Issue by cbfrank** [aspnet/AspLabs#64]
Hi
In the code ProxyAdvancedExtensions.cs, method `"CopyProxyHttpResponse"` use the code below to copy the proxy web headers:
`response.Headers[header.Key] = header.Value.ToArray()`
if any middleware executed beofre the proxy middleware append headers to response with the same name of the header from proxy web, then the existing headers will be overwrite.
Maybe the code shoulde check if a header with the key exist or not, if exisit, it should create a new array that contains values from both existing response header and proxy web headers.

Thanks

**Comment by davidfowl** [comment]
See https://github.com/microsoft/reverse-proxy for future proxy improvements
