### ISSUE TITLE
Return health check results as json in the 502 response

### ISSUE THREAD

**Issue by damienbod** [aspnet/AspLabs#7]

**Comment by damienbod** [comment]
Hi @anurse @glennc 

I'm going to return the check results in the body of the 502.

What do you think of this return DTO?

```
public class HealthCheckResults
{
	public Dictionary<string, HealthCheckResult> CheckResults { get; set; }
}

public class HealthCheckResult
{
	public CheckStatus CheckStatus { get; set; }
	public string Description { get; set; }
	public string AdditionalData { get; set; }
	public string CheckType { get; set; }
}

public enum CheckStatus
{
	Unknown,
	Failed,
	Ok,
	Warning
}
```
greetings Damien

**Comment by damienbod** [comment]
Have a working prototype here with results:

https://github.com/damienbod/AspLabs/tree/damienbod/add-results-healthcheck/src

http://localhost:5050/ , the external service will display the json results of the checks.

I want to add names with a dictionary so that the results can be grouped.

**Comment by damienbod** [comment]
https://github.com/aspnet/AspLabs/pull/14

**Comment by anurse** [comment]
As commented in the PR, it looks pretty good. I do think we should avoid adding properties until we've fully designed what they will look like and do. So let's just limit the `HealthCheckResult` to a `CheckStatus` and a `Description` for now.
