### ISSUE TITLE
StackOverflowException upon 404 for initial HEAD request

### ISSUE THREAD

**Issue by muqeet-khan** [aspnet/AspLabs#70]
If the API does not accept a HEAD request for the "set base" URL and returns a 404 then the REPL errors out with a StackOverflowException.  ("Process is terminating due to StackOverflowException.")

The base URL should probably accept a HEAD request? But, in case it does not, like the one I was trying, may be a more meaningful error will be helpful. 

Even though the base URL returned a 404, REPL still makes a request to a default swagger URL and in my case, that did return 200. So may be if both return 404 only then return an error?

Was able to observe this behavior with Fiddler as follows:

![image](https://user-images.githubusercontent.com/6345044/45447390-04b2a900-b695-11e8-8cc4-04d3a63a1757.png)

![image](https://user-images.githubusercontent.com/6345044/45447528-73900200-b695-11e8-92be-da6cddbae69d.png)

λ dotnet --version
2.2.100-preview2-009404

Also, Some of the keywords for HELP seem to be missing when I tried it out. I tried it in regular CMD prompt as well and got the same result. 

![image](https://user-images.githubusercontent.com/6345044/45447670-dbdee380-b695-11e8-9483-5a8c5eb875b5.png)

![image](https://user-images.githubusercontent.com/6345044/45447707-0630a100-b696-11e8-9ea9-77580be556bc.png)

**Comment by vijayrkn** [comment]
+@mlorbetske
