### ISSUE TITLE
Multipart/form-data request body read of bytes not always working

### ISSUE THREAD

**Issue by waynevdm** [aspnet/AspLabs#78]
Hi

I am using your proxy implementation on a project we are doing and it is really working well. I am just having a problem with a multipart/form-data POST. The error started happening when we started testing with an image of 52kb. What happens is that I have written a method to read all the bytes from the body of the request

        public static async Task<byte[]> GetRawBodyBytesAsync(HttpRequest request)
        {
            request.EnableRewind();
            using (var ms = new MemoryStream(2048))
            {
                await request.Body.CopyToAsync(ms);
                request.Body.Seek(0, SeekOrigin.Begin);
                return ms.ToArray();
            }
        }

The method works and fails at time because it returns a bunch of 00 bytes at the end of the array which is not valid.

Bytes portion

69-E6-B8-9A-A9-CA-74-94-A3-00-00-00-00-00-00-00

Have I done something wrong in how I am reading the bytes from the body for a multipart/form-data request? I want to read the bytes out and do some processing with them before the request is proxied.

Thanks,
Wayne

**Comment by waynevdm** [comment]
If anyone has the same problem this was a code issue. When the files are really large or there is network latency you can read the stream before it is completely written to. You should rather read the stream as follows.

        private byte[] ReadFully (Stream stream)
        {
            byte[] buffer = new byte[32768];
            using (MemoryStream ms = new MemoryStream())
            {
                while (true)
                {
                    int read = stream.Read (buffer, 0, buffer.Length);
                    if (read <= 0)
                        return ms.ToArray();
                    ms.Write (buffer, 0, read);
                }
            }
        }

**Comment by cpboyd** [comment]
With a 200MB file, I'm effectively reaching a stall of the POST.

I've also noticed that the CLI reports multiple instances of the POST occurring (right after one another, which is probably contributing to these issues).  The browser, on the other hand, only reports a single POST, so it's probably retrying the same request because it wasn't acknowledged.

Smaller files don't exhibit this behavior.

@waynevdm What was the largest size file you handled?  Were you able to handle it within `CreateProxyHttpRequest` or did you create separate functions?

I've also tried reading the `request.Body` into a file, but the file never seems to have anything written to it.

**Comment by waynevdm** [comment]
We were testing with 10 to 20mb files. I don't think HTTP is the best protocol to use to download really large files. We read the data out before calling CreateProxyHttpRequest.

**Comment by cpboyd** [comment]
@waynevdm HTTP may not be optimal, but I was trying to integrate with [SWUpdate](https://sbabic.github.io/swupdate/swupdate.html) which provides its own internal Mongoose webserver that processes the update as it's uploaded.

Smaller files work fine and I'd rather not read it all into a temporary file (as SWUpdate creates its own temporary file too).

**Comment by cpboyd** [comment]
It turns out that my specific issue is actually related to the fact that ASP.NET Core enforces a 30MB file limit by default:
https://www.talkingdotnet.com/how-to-increase-file-upload-size-asp-net-core/

**Comment by davidfowl** [comment]
All proxy work has moved to https://github.com/microsoft/reverse-proxy.
