### ISSUE TITLE
Use a collection of URLs instead of a single URL for the AddUrlCheck

### ISSUE THREAD

**Issue by damienbod** [aspnet/AspLabs#8]

**Comment by damienbod** [comment]
Added a check for multiple URL checks.

If all url checks are successful => check OK, status SUCCESS
If all url checks fail => check FAILED, status FAILED
If one >1 failed and not all success => check SUCCESS, status WARNING

What do you think?

part of https://github.com/aspnet/AspLabs/pull/14

Greetings Damien

**Comment by damienbod** [comment]
@glennc @anurse 
I would like to extend this method so that the check can be configured.
Default: If one >1 failed and not all success =>  status Warning.
Strict: If one >1 failed and not all success => status Unhealthy.

OK?

Also, is it OK that I continue to add features, checks? I know you are very busy and don't have time.

Greetings Damien

**Comment by damienbod** [comment]
https://github.com/aspnet/AspLabs/pull/15

**Comment by natemcmaster** [comment]
Closing as this issue is stale. HealthChecks has moved into production. Use https://github.com/aspnet/AspNetCore for issues on this feature in the future.
