### ISSUE TITLE
[Feature Request]: Please update nuget for Microsoft.AspNetCore.Proxy

### ISSUE THREAD

**Issue by oliverjanik** [aspnet/AspLabs#86]
Reopening: #2794

`<rant>`
What's with the bloody bots running around closing long standing feature requests? The issue is open because it has not been resolved yet. Seems every repo has a bot you have to fight, lately.
This one is special because not only it closes discussion it locks it as well, just in case you wanted to respond.
`</rant>`

**Comment by denmitchell** [comment]
Is a NuGet package for Proxy available via the Arcade feed or MyGet?  If so, what is the package?

**Comment by davidfowl** [comment]
All proxy work has moved to https://github.com/microsoft/reverse-proxy.
