### ISSUE TITLE
How to make proxy work that preserver original request URL as Nginx? Does it support?

### ISSUE THREAD

**Issue by RonnyRen** [aspnet/AspLabs#87]
Example:
The Application Server: Name "VMApp", ASPNET Core API project
The access URL is http://VMApp:8011/api/values

The ASPNET Core Proxy Server: Name "VMAppProxy", ASPNET Core Web Application project
ASPNet Core 2.1 project
Proxy setting:
![image](https://user-images.githubusercontent.com/33855404/41325718-b17a4926-6e70-11e8-93c8-db2e79b726e1.png)
![image](https://user-images.githubusercontent.com/33855404/41325758-de200b8c-6e70-11e8-89c4-0b4c15ce1c37.png)
The access URL is http://VMAppProxy:8090
Access API through ASPNET Core Proxy Server:
URL: http://VMAppProxy:8090/api/values
The URL is the URL accessed from Proxy Server as following in the log file, How to preserver the Original request URL like Nginx?
2018-06-12 00:35:01.6257|1|Microsoft.AspNetCore.Hosting.Internal.WebHost|INFO|  Request starting HTTP/1.1 GET http://VMApp:8011/api/values

The Nginx Proxy Server: Name "VMNginx", listen 8090 port and proxy_pass is http://apinginx.com;
 upstream apinginx.com{
        ip_hash;
        server VMApp:8011;
}
Access API from Nginx Proxy Server:
URL: http://apinginx.com:8090/api/values
The URL is Original request URL as following in the log file:
2018-06-12 00:35:05.7824|1|Microsoft.AspNetCore.Hosting.Internal.WebHost|INFO|  Request starting HTTP/1.0 GET http://apinginx.com/api/values

**Comment by davidfowl** [comment]
All proxy work has moved to https://github.com/microsoft/reverse-proxy.
