### ISSUE TITLE
Websocket through proxy not working (2.1.0 rc 1 and .NET Core 2.1)

### ISSUE THREAD

**Issue by InnovistaLucia** [aspnet/AspLabs#88]
We are using self-hosted services with recent .NET Core 2.1 RC and the corresponding aspnetcore components. These microservices should run on several internal ports and the only public access should be via a proxy software (former node.js now .NET Core 2.1 also). We try to use the Microsoft.AspNetCore.Proxy Component [https://github.com/aspnet/Proxy](url) V 0.2.
The proxy should also forward websocket requests but the websocket connection Handshake fails when using the proxy.

```C#
public async Task InitWSAsync(HttpContext context, WebSocket pSocket)
{
                var buffer = new byte[1024 * 8];
                WebSocketReceiveResult result = await pSocket.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
                string lMsgString = System.Text.Encoding.UTF8.GetString(buffer, 0, result.Count);...
```
The code stops on the ReceiveAsync line and does not continue properly. Firefox shows a handshake failed after a timeout.
When accessing the microservice directly the runtime continues and receives a message String correctly.

I've attached a Test-Project with a simple Proxy App and a Service App where you can find the whole configuration of the webhost, kestrel etc..
To test the faulty Proxy access run both projects and open "http://localhost:8080/websocket.html" in the browser. To test the successfull direct Service access run the Service App only and open "http://localhost:1800/websocket2.html".
[NETCoreProxyTest.zip](https://github.com/aspnet/Home/files/2047624/NETCoreProxyTest.zip)

**Comment by davidfowl** [comment]
All proxy work has moved to https://github.com/microsoft/reverse-proxy.
