### ISSUE TITLE
.Net Core 2.1 for Proxy

### ISSUE THREAD

**Issue by byzheng** [aspnet/AspLabs#89]
I am trying to use Proxy package (https://github.com/aspnet/Proxy), but get error about `AddProxy` is not defined. See details from here: https://stackoverflow.com/questions/42000362/creating-a-proxy-to-another-web-api-with-asp-net-core

Then I tried to compile the package from source codes. Add get an error about 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.	Microsoft.AspNetCore.Proxy.Samples	C:\Program Files\dotnet\sdk\2.1.4\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	135	
```

**Comment by davidfowl** [comment]
All proxy work has moved to https://github.com/microsoft/reverse-proxy.
