### ISSUE TITLE
Enable dynamic routing

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#91]
_From @ycrumeyrolle on Tuesday, October 20, 2015 3:02:41 PM_

The proxy should be able to send the underlying request to different hosts based on the request context.

For example
Incoming request: https://mysite.com/api1/
Outgoing request : http://myapi1.local/

Incoming request: https://mysite.com/api2/
Outgoing request : http://myapi2.local/

We could imagine a IProxyRouter. Default implementation is a DirectProxyRouter (the current implementation). Other implementation could be a rule-based router.
This will allow to have a basic reverse proxy.

_Copied from original issue: aspnet/Proxy#10_

**Comment by davidfowl** [comment]
All proxy work has moved to https://github.com/microsoft/reverse-proxy.
