### ISSUE TITLE
Strip Content-Length header when Transfer-Encoding header is set on request and response

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#93]
_From @halter73 on Wednesday, October 12, 2016 4:50:40 PM_

I seems the HTTP the spec suggests removing the content-length header when a transfer-encoding header is set.

>   If a message is received with both a Transfer-Encoding and a
>    Content-Length header field, the Transfer-Encoding overrides the
>    Content-Length.  Such a message might indicate an attempt to
>    perform request smuggling (Section 9.5) or response splitting
>    (Section 9.4) and ought to be handled as an error.  A sender MUST
>    remove the received Content-Length field prior to forwarding such
>    a message downstream.
> https://tools.ietf.org/html/rfc7230#section-3.3.3

https://github.com/aspnet/KestrelHttpServer/pull/1163#discussion_r83061038

_Copied from original issue: aspnet/Proxy#30_

**Comment by davidfowl** [comment]
All proxy work has moved to https://github.com/microsoft/reverse-proxy.
