### ISSUE TITLE
Adding additional Headers?

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#95]
_From @dorlandode on Saturday, December 10, 2016 9:56:29 AM_

What do you think about adding the ability to add additional headers to the proxy request.  For example, Authorization: Basic SomeBase64String

I was thinking of adding Headers as an IDictionary<string, string> property on the ProxyOptions.

Then in the ProxyMiddleware adding this on line 84:
            // Add additional headers
            foreach(var header in _options.Headers){
                 if (!requestMessage.Headers.TryAddWithoutValidation(header.Key, header.Value) && requestMessage.Content != null)
                {
                    requestMessage.Content?.Headers.TryAddWithoutValidation(header.Key, header.Value);
                }
            }

_Copied from original issue: aspnet/Proxy#35_

**Comment by davidfowl** [comment]
See https://github.com/microsoft/reverse-proxy for future proxy improvements
