### ISSUE TITLE
NETStandard as global dependency

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#96]
_From @mrapan on Monday, December 19, 2016 7:15:20 AM_

It looks like NETStandard.Library is a global dependency in project.json, this leads to .NET Core dependencies even if targeting full framework.

_Copied from original issue: aspnet/Proxy#36_

**Comment by davidfowl** [comment]
All proxy work has moved to https://github.com/microsoft/reverse-proxy.
