### ISSUE TITLE
Feature Request - Add web socket/SignalR support

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#98]
_From @davidpeden3 on Thursday, January 5, 2017 6:48:13 AM_

It would be great to be able to utilize SignalR behind a Kestrel-hosted reverse proxy.

_Copied from original issue: aspnet/Proxy#38_

**Comment by davidfowl** [comment]
See https://github.com/microsoft/reverse-proxy for future proxy improvements
