### ISSUE TITLE
Refactoring ProxyMiddleware

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#99]
_From @Marusyk on Thursday, February 23, 2017 2:47:48 PM_

Made refactoring for ProxyMiddleware.

Added two methods `CreateRequestMessage` and `CopyResponseAsync` to use in `Invoke`

It makes some improve of reading the code

_Copied from original issue: aspnet/Proxy#44_

**Comment by davidfowl** [comment]
See https://github.com/microsoft/reverse-proxy for future proxy improvements
